import Product from "../../components/product/product";
import "./style.css";
async function getProducts() {
  const res = await fetch("https://fakestoreapi.com/products", {
    cache: "no-store", //SSR ->getServerSideProps
  });

  console.log("Fetching");
  return res.json();
}

export default async function ProductsPage() {
  const products = await getProducts();
  console.log("rendering products");
  return (
    <>
      <h1>Products Page Generated by SSR</h1>
      <div className="grid">
        {products.map((product) => (
          <Product product={product} />
        ))}
      </div>
    </>
  );
}
